###

POST http://localhost:5002/app/users/
Content-type: application/json

{
    "username": "test3",
    "password": "test111"
}

###

POST http://localhost:5002/app/users/login HTTP/1.1
Content-type: application/json

{
    "username": "test3",
    "password": "test111"
}





###

GET http://localhost:5002/app/boards/
Content-type: application/json


###

GET http://localhost:5000

